language: node_js
cache: yarn
node_js:
- '9'
script:
- yarn test
- yarn dist
git:
  submodules: false
notifications:
  email: false
  slack:
    secure: UPhosE0ytoAKBy9FTY41sERHuU+Zy14404TUhS6eT4Og4+/ECW3TNliBfX1xiXl41l5+wypjWDfHkPMZIiZjRfuWGe/eIdX8zEZKXLiO5Ji9idcJsD1Y3nesH1846UrbdywZ/I6k8z3xHuZfr4kAyhSnmQ1TjPqBUVwU2fCkT+c+USmRx1c7QZ2yCoKXLHaVYjZQ4vvJqrR2f/mNa72oC+Zmuvfq1uADjl7nsVaHaT1V9bClhfh3tFIb+MpzLPhFjftwJHOhUNbwQNzZD5Odi0KZVeoKS6NQXOkumGODvA9j9zWljiNnQyh+pGPH7vOBn9KO5x2ZnOAjWu1W+2b+SoXTT0rBm2XCy4aHL/a12fUTfLUWUDqg19aeCPs86i5Hhv/RLqKLfXeV4QdXVRC/g04U9XI4bwpv/lMv0sQM0GrzOzM1cKGKL5zDFK3EtfkjBpcMO7/S22QjLYCswNiSJ/SoabKHURt3/j8ZnmXEhczUi6mJl0w/pMxOyhSGHQwCf2xpz/U//GSZvUGIeh9CJ/vQfNmvE/ZOJTe3BpWeZHAllnByS4C9e5Tz+plef1eXuY3qolUyDrZ7WfWMVMA/9m81XQ2DBJPx5bOTexvYnFVr5tPDyBZ9otw8sUdyxn0wCQf+/6XMuB0myY+42UA3zfeByLn5LXNJtSaaL35PP88=
    on_success: change
    on_failure: always
deploy:
- provider: npm
  skip_cleanup: true
  email: roman.stranghoener@innoq.com
  api_key:
    secure: mcy4y8KS6ZDIWYLVgBentn5wv9HJ+YU6ChWruKaTKnmW9P2cmgRGSyh040vAPIZlUrgcmm0VgR2p4pvwqrFEGA4wEyIZnWWt47dtP+kGhjBW0VnwO7xhbp2V7PHMk33dhQF3a+BgH/g63HZ1nZDMAi6D8ijPRAU9jqTHpHtWo9S5YvePQ5ndUOECZ6NqgyuR7oqPFxhGVxHtZtna3S4moVHiegiwhEpZMzALARG9sS3gZMTXZ3EFySbI5XQ78ckjmliMtKTqmFzvvDc9qFyTaQOrROnz6N2qp6wjk0QXFqay5Pah/U+wqpl8HC0GyXCfdZ/VwkJWb+coWk9dk6wIVZGGKXpoU3cDxE+2/Hm4iR64PZHAH0TuwMvr1qUop7LViJMIrW4ovw5XkaMaQy4Vzlqiend4/yZaD0ItYqPf8y9yey39V9/RtR0e29p51DZZJUm8f+vM4hJm+GOki/1h2nHDZ5LsU+QnEGFTmQ0Eog6OnqNAuMCRKy5DJrNXTDk45+JwgNYyOSm3lfpe+nDdw38dExLW7YpTlxenRyAvZCLbX6LO9jlABV2k0FNNDtBpGVOgXpvyJU0ub0sXHDjLPd8/wJGzrhumn+AjbYgGr9wCvQ378XxSiHQRwuMUK2IJi0x/H9E4d7svRjt1sqnRSRjbS5p7+X+1jzEF+T5EqmI=
  on:
    tags: true
    repo: innoq/innoq-bootstrap-theme
